const { Ci } = require('chrome'); // https://addons.mozilla.org/en-US/developers/docs/sdk/latest/dev-guide/tutorials/chrome.html

exports.SSDPServiceType = 'ssdp:all';
exports.MatchStickMacAddresses = ['98:3B:16', '02:1A:11'];
exports.MatchstickModelName = 'MatchStick';
exports.ChromecastModelName = 'Eureka Dongle';

exports.MSearch = 'M-SEARCH * HTTP/1.1\r\n' +
                'HOST: {0}:{1}\r\n' +
                'ST: {2}\r\n' +
                'MAN: "ssdp:discover"\r\n' +
                'MX: 1\r\n\r\n';

exports.FilePickerConstants = Ci.nsIFilePicker;


exports.ServiceTypes = [
	["Address Book", "urn:schemas-upnp-org:service:AddressBook:1"],
	["AV Transport 1", 'urn:schemas-upnp-org:service:AVTransport:1'],
	["AV Transport 2", 'urn:schemas-upnp-org:service:AVTransport:2'],
	["AV Transport 3", 'urn:schemas-upnp-org:service:AVTransport:3'],
	["Basic Management 1", "urn:schemas-upnp-org:service:BasicManagement:1"],
	["Basic Management 2", "urn:schemas-upnp-org:service:BasicManagement:2"],
	["Calendar", "urn:schemas-upnp-org:service:Calendar:1"],
	["Call Management 1", "urn:schemas-upnp-org:service:CallManagement:1"],
	["Call Management 2", "urn:schemas-upnp-org:service:CallManagement:2"],
	["Configuration Management 1", "urn:schemas-upnp-org:service:ConfigurationManagement:1"],
	["Configuration Management 2", "urn:schemas-upnp-org:service:ConfigurationManagement:2"],
	["Connection Manager 1", 'urn:schemas-upnp-org:service:ConnectionManager:1'],
	["Connection Manager 2", 'urn:schemas-upnp-org:service:ConnectionManager:2'],
	["Connection Manager 3", 'urn:schemas-upnp-org:service:ConnectionManager:3'],
	["Content Directory 1", 'urn:schemas-upnp-org:service:ContentDirectory:1'],
	["Content Directory 2", 'urn:schemas-upnp-org:service:ContentDirectory:2'],
	["Content Directory 3", 'urn:schemas-upnp-org:service:ContentDirectory:3'],
	["Content Directory 4", 'urn:schemas-upnp-org:service:ContentDirectory:4'],
	["Content Sync", "urn:schemas-upnp-org:service:ContentSync:1"],
	["Control Valve", "urn:schemas-upnp-org:service:controlValve:1"],
	["Data Store", "urn:schemas-upnp-org:service:DataStore:1"],
	["Device Protection", "urn:schemas-upnp-org:service:DeviceProtection:1"],
	["Device Security", "urn:schemas-upnp-org:service:DeviceSecurity:1"],
	["DIAL Multiscreen", 'urn:dial-multiscreen-org:service:dial:1'],
	["Digital Security Camera Settings", "urn:schemas-upnp-org:service:DigitalSecurityCameraSettings:1"],
	["Digital Security Camera Still Image", "urn:schemas-upnp-org:service:DigitalSecurityCameraStillImage:1"],
	["Digital Security Camera Motion Image", "urn:schemas-upnp-org:service:DigitalSecurityCameraMotionImage:1"],
	["Dimming", "urn:schemas-upnp-org:service:DimmingService:1 "],
	["Energy Management", "urn:schemas-upnp-org:service:EnergyManagement:1"],
	["External Activity", "urn:schemas-upnp-org:service:ExternalActivity:1"],
	["Fan Speed", "urn:schemas-upnp-org:service:FanSpeed:1"],
	["Feeder", "urn:schemas-upnp-org:service:Feeder:1"],
	["HVAC User Operating Mode", "urn:schemas-upnp-org:service:HVAC_UserOperatingMode:1"],
	["HVAC Fan Operating Mode", "urn:schemas-upnp-org:service:HVAC_FanOperatingMode:1"],
	["HVAC Setpoint Schedule", "urn:schemas-upnp-org:service:HVAC_SetpointSchedule:1"],
	["Inbound Connection Config", "urn:schemas-upnp-org:service:InboundConnectionConfig:1"],
	["Input Config", "urn:schemas-upnp-org:service:InputConfig:1"],
	["IRCC", 'urn:schemas-sony-com:service:IRCC:1'],
	["Link Authentication", "urn:schemas-upnp-org:service:LinkAuthentication:1"],
	["Layer 3 Forwarding", 'urn:schemas-upnp-org:service:Layer3Forwarding:1'],
	["Low Power", "urn:schemas-upnp-org:service:LowerPowerDevice:1"],
	["Media Management 1", "urn:schemas-upnp-org:service:MediaManagement:1"],
	["Media Management 2", "urn:schemas-upnp-org:service:MediaManagement:2"],
	["Media Receiver Registrar", 'urn:microsoft.com:service:X_MS_MediaReceiverRegistrar:1'],
	["Messaging 1", "urn:schemas-upnp-org:service:Messaging:1"],
	["Messaging 2", "urn:schemas-upnp-org:service:Messaging:2"],
	["Microsoft Windows Peer Name Resolution Protocol", 'urn:Microsoft Windows Peer Name Resolution Protocol: V4:IPV6:LinkLocal'],
	["Party", 'urn:schemas-sony-com:service:Party:1'],
	["Presence", "urn:schemas-upnp-org:service:Presence:1"],
	["Print Basic", "urn:schemas-upnp-org:service:PrintBasic:1"],
	["Print Enhanced Layout", "urn:schemas-upnp-org:service:PrintEnhancedLayout:1"],
	["QoS Device 1", "urn:schemas-upnp-org:service:QosDevice:1"],
	["QoS Device 2", "urn:schemas-upnp-org:service:QosDevice:2"],
	["QoS Device 3", "urn:schemas-upnp-org:service:QosDevice:3"],
	["QoS Manager 1", "urn:schemas-upnp-org:service:QosManager:1"],
	["QoS Manager 2", "urn:schemas-upnp-org:service:QosManager:2"],
	["QoS Manager 3", "urn:schemas-upnp-org:service:QosManager:3"],
	["QoS Policy Holder 1", "urn:schemas-upnp-org:service:QosPolicyHolder:1"],
	["QoS Policy Holder 2", "urn:schemas-upnp-org:service:QosPolicyHolder:2"],
	["QoS Policy Holder 3", "urn:schemas-upnp-org:service:QosPolicyHolder:3"],
	["Radius Client", "urn:schemas-upnp-org:service:RadiusClient:1"],
	["Remote Access Discovery Agent Sync 1", "urn:schemas-upnp-org:service:RADASync:1"],
	["Remote Access Discovery Agent Sync 2", "urn:schemas-upnp-org:service:RADASync:2"],
	["Remote Access Discovery Agent Config 1", "urn:schemas-upnp-org:service:RADAConfig:1"],
	["Remote Access Discovery Agent Config 2", "urn:schemas-upnp-org:service:RADAConfig:2"],
	["Remote Access Transport Agent Config", "urn:schemas-upnp-org:service:RATAConfig:1"],
	["Remote UI Client", "urn:schemas-upnp-org:service:RemoteUIClient:1"],
	["Remote UI Server", "urn:schemas-upnp-org:service:RemoteUIServer:1"],
	["Rendering Control", 'urn:schemas-upnp-org:service:RenderingControl:1'],
	["Samsung Multiscreen", "urn:samsung.com:service:MultiScreenService:1"],
	["Scan", "urn:schemas-upnp-org:service:Scan:1"],
	["Scheduled Recording 1", "urn:schemas-upnp-org:service:ScheduledRecording:1"],
	["Scheduled Recording 2", "urn:schemas-upnp-org:service:ScheduledRecording:2"],
	["Security Console", "urn:schemas-upnp-org:service:SecurityConsole:1"],
	["Sensor Transport Geneic", "urn:schemas-upnp-org:service:SensorTransportGeneric:1"],
	["Software Management 1", "urn:schemas-upnp-org:service:SoftwareManagement:1"],
	["Software Management 2", "urn:schemas-upnp-org:service:SoftwareManagement:2"],
	["Switch Power", "urn:schemas-upnp-org:service:SwitchPower:1 "],
	["Temperature Sensor", "urn:schemas-upnp-org:service:TemperatureSensor:1"],
	["Temperature Setpoint", "urn:schmeas-upnp-org:service:TemperatureSetpoint:1"],
	["Two Way Motion Motor", "urn:schemas-upnp-org:service:TwoWayMotionMotor:1"],
	["WAN Common Interface Config", 'urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1'],
	["WAN IP Connection", 'urn:schemas-upnp-org:service:WANIPConnection:1'],
	["WAN PPP Connection", 'urn:schemas-upnp-org:service:WANPPPConnection:1'],
	["WLAN Configuration", "urn:schemas-upnp-org:service:WLANConfiguration:1"],
	["WFA WLAN Config", 'urn:schemas-wifialliance-org:service:WFAWLANConfig:1'],
	["XCIS", 'urn:schemas-sony-com:service:X_CIS:1']
];
exports.DeviceTypes = [
	["Basic", "urn:schemas-upnp-org:device:Basic:1"],
	["Binary Light", "urn:schemas-upnp-org:device:BinaryLight:1"],
	["DIAL Multiscreen", 'urn:dial-multiscreen-org:device:dial:1'],
	["Digital Security Camera", "urn:schemas-upnp-org:device:DigitalSecurityCamera:1"],
	["HVAC", "urn:schemas-upnp-org:device:HVAC_System:1"],
	["HVAC Zone Thermostat", "urn:schemas-upnp-org:device:HVAC_ZoneThermostat:1"],
	["Internet Gateway 1", "urn:schemas-upnp-org:device:InternetGatewayDevice:1"],
	["Internet Gateway 2", "urn:schemas-upnp-org:device:InternetGatewayDevice:2"],
	["Light", "urn:schemas-upnp-org:device:Light:1"],
	["Manageable Device 1", "urn:schemas-upnp-org:device:ManageableDevice:1"],
	["Manageable Device 2", "urn:schemas-upnp-org:device:ManageableDevice:2"],
	["Media Renderer 1", "urn:schemas-upnp-org:device:MediaRenderer:1"],
	["Media Renderer 2", "urn:schemas-upnp-org:device:MediaRenderer:2"],
	["Media Renderer 3", "urn:schemas-upnp-org:device:MediaRenderer:3"],
	["Media Server 1", "urn:schemas-upnp-org:device:MediaServer:1"],
	["Media Server 2", "urn:schemas-upnp-org:device:MediaServer:2"],
	["Media Server 3", "urn:schemas-upnp-org:device:MediaServer:3"],
	["Media Server 4", "urn:schemas-upnp-org:device:MediaServer:4"],
	["Printer", "urn:schemas-upnp-org:device:printer:1"],
	["Remote Access Client", "urn:schemas-upnp-org:device:RAClient:1"],
	["Remote Access Discovery Agent", "urn:schemas-upnp-org:device:RADiscoveryAgent:2"],
	["Remote Access Server 1", "urn:schemas-upnp-org:device:RAServer:1"],
	["Remote Access Server 2", "urn:schemas-upnp-org:device:RAServer:2"],
	["Remote UI Client", "urn:schemas-upnp-org:device:RemoteUIClientDevice:1"],
	["Remote UI Server", "urn:schemas-upnp-org:device:RemoteUIServerDevice:1"],
	["Root", 'upnp:rootdevice'],
	["Scanner", "urn:schemas-upnp-org:device:Scanner:1"],
	["Sensor Management", "urn:schemas-upnp-org:device:SensorManagement:1"],
	["Solar Protection Blind", "urn:schemas-upnp-org:device:SolarProtectionBlind:1"],
	["Telephony Client 1", "urn:schemas-upnp-org:device:TelephonyClient:1"],
	["Telephony Client 2", "urn:schemas-upnp-org:device:TelephonyClient:2"],
	["Telephony Server 1", "urn:schemas-upnp-org:device:TelephonyServer:1"],
	["Telephony Server 2", "urn:schemas-upnp-org:device:TelephonyServer:2"],
	["WAN", 'urn:schemas-upnp-org:device:WANDevice:1'],
	["WAN Connection", 'urn:schemas-upnp-org:device:WANConnectionDevice:1'],
	["WLAN Access Point", "urn:schemas-upnp-org:device:WLANAccessPointDevice:1"],
	["WFA", 'urn:schemas-wifialliance-org:device:WFADevice:1']
];